In [6]:
import pandas as pd
import numpy as np
serd=pd.Series(range(6),
index=['white','white','blue','green','green','yellow'])
serd

white     0
white     1
blue      2
green     3
green     4
yellow    5
dtype: int64

In [7]:
serd['white']

white    0
white    1
dtype: int64

In [8]:
serd.index.is_unique

False

In [14]:
import pandas as pd
data = {'colors': ['red', 'blue', 'green', 'yellow', 'black'],
        'items': ['ball', 'pen', 'pencil', 'eraser', 'sharpener'],
        'price': [2000, 1000, 3000, 5000, 4000]}
frame = pd.DataFrame(data)
frame

   colors      items  price
0     red       ball   2000
1    blue        pen   1000
2   green     pencil   3000
3  yellow     eraser   5000
4   black  sharpener   4000

In [15]:
frame.loc[2,'price']=55

In [16]:
frame.index.is_unique

True

In [11]:
ser3=pd.Series([1,5,6,3],index=[0,3,5,6])
ser3

0    1
3    5
5    6
6    3
dtype: int64

In [12]:
ser3.reindex(range(0,6))

0    1.0
1    NaN
2    NaN
3    5.0
4    NaN
5    6.0
dtype: float64

In [13]:
ser3.reindex(range(0,6),method='ffill')

0    1
1    1
2    1
3    5
4    5
5    6
dtype: int64

In [ ]:
frame.reindex(range(5),method='ffill',columns=['item','price'])

In [ ]:
ser=pd.Series(np.arange(4.),
index=[''])

In [21]:
frame.drop(1)

   colors      items  price
0     red       ball   2000
2   green     pencil     55
3  yellow     eraser   5000
4   black  sharpener   4000

In [23]:
dfwithout_new =frame.drop('New',axis=1)

KeyError: "['New'] not found in axis"

In [24]:
frame.drop('New',axis=1,inplace=True)

KeyError: "['New'] not found in axis"

In [27]:
frame1=pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['red','blue','yellow','white'],
                    columns=['ball','pen','pencil','paper'])
frame1

        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [28]:
np.sqrt(frame1)

            ball       pen    pencil     paper
red     0.000000  1.000000  1.414214  1.732051
blue    2.000000  2.236068  2.449490  2.645751
yellow  2.828427  3.000000  3.162278  3.316625
white   3.464102  3.605551  3.741657  3.872983

In [29]:
f=lambda x:x.max() -x.min()

In [ ]:
#second way for function declaration
def f(x):
    return x.max() - x.min()

In [36]:
frame1.apply(f,axis=0)

ball      12
pen       12
pencil    12
paper     12
dtype: int64

In [37]:
frame1.apply(f,axis=1)

red       3
blue      3
yellow    3
white     3
dtype: int64

In [39]:
def f(x):
    return pd.Series([x.min(),x.max()],
                    index=['min','max'])

In [40]:
frame1.apply(f)

     ball  pen  pencil  paper
min     0    1       2      3
max    12   13      14     15

In [42]:
ser =pd.Series([5,0,3,8,4],
        index=['red','blue','yellow','white','green'])
ser

red       5
blue      0
yellow    3
white     8
green     4
dtype: int64

In [45]:
ser.sort_index()

blue      0
green     4
red       5
white     8
yellow    3
dtype: int64

In [46]:
ser.sort_index(ascending=False)

yellow    3
white     8
red       5
green     4
blue      0
dtype: int64

In [47]:
ser.sort_values()

blue      0
yellow    3
green     4
red       5
white     8
dtype: int64

In [ ]:
ser.rank()

red       4.0
blue      1.0
yellow    2.0
white     5.0
green     3.0
dtype: float64

In [49]:
ser.rank(method='first')

red       4.0
blue      1.0
yellow    2.0
white     5.0
green     3.0
dtype: float64

In [50]:
ser.rank(method='first',ascending=False)

red       2.0
blue      5.0
yellow    4.0
white     1.0
green     3.0
dtype: float64

In [44]:
frame2=pd.DataFrame(np.arange(12).reshape((4,3)),
                    index=['blue','green','white','yellow'],
                    columns=['ball','pen','pencil'])
frame2

        ball  pen  pencil
blue       0    1       2
green      3    4       5
white      6    7       8
yellow     9   10      11